### ISSUE TITLE
Add an option to move the HUD

### ISSUE THREAD

**Issue by Scarlaid** [AdvancedXRay/Auto-Clicker#26]
**Is your feature request related to a problem? Please describe.**
Yes, the HUD that display whenever you are using AutoClicker from this mod or not
It kinda "in the way" with other HUDs

**Describe the solution you'd like**
Maybe an option to change the X/Y Offset

**Describe alternatives you've considered**
Similar but maybe draggable?

**Additional context**
![image](https://user-images.githubusercontent.com/90851437/197145004-3646ef1c-0e44-4c19-a91c-34a726bca752.png)

**Comment by iambeingtracked** [comment]
Agreed, we need something like this.
