### ISSUE TITLE
Increase maximum time between clicks to above 50 ticks

### ISSUE THREAD

**Issue by metagn** [AdvancedXRay/Auto-Clicker#38]
**Is your feature request related to a problem? Please describe.**
Currently, the maximum wait time/slowest speed between clicks for the spamming mode is 50 ticks in the options menu. This is uncomfortable (although enough) for things like [zombie reinforcement drowned farms](https://www.youtube.com/watch?v=JyHqXBC9W24), which need to wait 45 seconds for zombie to convert into drowned (which works with something like 45 ticks, but can have issues on lower TPS servers). 

**Describe the solution you'd like**
Increase the time to something like 100 ticks.

**Describe alternatives you've considered**
Allow setting the max ticks in the config for more precise sliders.

**Comment by c0nstexpr** [comment]
Suggest to extend the auto action interval to 1 minute long, which is about 60*20=1200 ticks. Or just let user use keyboard to input the interval number.
