### ISSUE TITLE
Link mod config to ModMenu

### ISSUE THREAD

**Issue by AdyTech99** [AdvancedXRay/Auto-Clicker#59]
**Is your feature request related to a problem? Please describe.**
Right now, opening the mod's config screen takes up an entire key-bind which could have been used for something else.

**Describe the solution you'd like**
The config should be linked to the "open config" button in Mod Menu.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by MichaelHillcox** [comment]
I don't see any real issue with this but I'd still want the button bind by default

**Comment by AdyTech99** [comment]
Yes, the button bind is still available.
