### ISSUE TITLE
Forge port!

### ISSUE THREAD

**Issue by denny4-user** [AdvancedXRay/Auto-Clicker#64]

**Comment by MichaelHillcox** [comment]
Make me!

**Comment by denny4-user** [comment]
please =)

**Comment by MichaelHillcox** [comment]
Neoforge and that's my last offer

**Comment by denny4-user** [comment]
=(

**Comment by denny4-user** [comment]
>:)

**Comment by MichaelHillcox** [comment]
I'm keeping this open as I plan to port the mod to all mod loaders as it's a simple mod

**Comment by denny4-user** [comment]
Please notify me if you do anything, any ports on Forge :3

**Comment by MichaelHillcox** [comment]
It's now available for 1.21.1 Neoforge
